---
title: "vizpackage"
output:
  word_document: default
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#' Package Installation and Calling
#' 
#' Quickly install and load packages for creating visual analytics in R.
#' 
```{r}
vizpackages <- function() {
  install.packages("colourpicker")
  library(colourpicker)
  install.packages("RColorBrewer")
  library(RColorBrewer)
  install.packages("esquisse")
  library(esquisse)
  install.packages("ggplot2")
  library(ggplot2)
  install.packages("ggvis")
  library(ggvis)
  install.packages("ggalt")
  library(ggalt)
  install.packages("lattice")
  library(lattice)
  install.packages("plotly")
  library(plotly)
  library(ggcorrplot)
  install.packages("quantmod")
  library(quantmod)
  print("Basic packages for data visualization now installed.")
  print("ColourPicker, RColorBrewer, Esquisse, GGPlot2, GGVis, Lattice, Plotly")
}
```

#' Basic Plots
#'
#' Easily create basic plots using gggplot2
#' 
#' @param 'mpg' data used for examples in basic plots
#' 

```{r}
#' Create a scatter plot
#' @example scatterplot(mpg, cyl, cty)
scatter.plot <- function(data, x, y) {
  ggplot(data, aes({{x}}, {{y}})) +
    geom_point(color = "red") +
    theme_bw()
}
#' Create a line plot
#' @example line.plot(mpg, cyl, cty)
line.plot <- function(data, x, y) {
  ggplot(data, aes({{x}}, {{y}})) +
    geom_line(color = "blue") +
    theme_bw()
}
#' Create a histogram 
#' @example histogram.plot(mpg, displ)
histogram.plot <- function(data, x, y) {
  ggplot(data, aes({{x}}, {{y}})) +
    geom_histogram(fill = "green", binwidth = .5, col = "black", size = .1) +
    theme_classic()
}
#' Create a box plot
#' @example box.plot(mpg, class, cty)
box.plot <- function(data, x, y) {
  ggplot(data, aes({{x}}, {{y}})) +
    geom_boxplot(varwidth = TRUE, fill = "purple") +
    theme_classic()
}
#' Create a jitter plot
#' @example jitter.plot(mpg, cty, hwy)
jitter.plot <- function(data, x, y) {
  ggplot(data, aes({{x}}, {{y}})) +
  geom_jitter(width = .5, size = 1) +
  theme_bw()
}
#' Create a jitter plot with smooth line
#' @example jitter.smooth(mpg, cty, hwy)
jitter.smooth <- function(data, x, y) {
  ggplot(data, aes({{x}}, {{y}})) +
    geom_point() +
    geom_smooth(method = "lm", se = F) +
    theme_bw()
}
#' Create a violin plot
#' @example violin.plot(mpg, class, cty)
violin.plot <- function(data, x, y) {
  ggplot(data, aes({{x}}, {{y}})) +
    geom_violin() +
    theme_bw()
}
```

#'
#'
#' Advanced Plot Functions
#' 
#' Easily create more advanced plots using ggplot2
#' 
#' @param 'mtcars' and 'mpg' used for examples
#' 
```{r}
#' Create a counts plot
#' @example count.plot(mpg, cty, hwy)
count.plot <- function(data, x, y) {
  ggplot(data, aes({{x}}, {{y}})) +
    geom_count(col = "dodgerblue2") +
    theme_bw()
}
#' Create correlation plot
#' @example corr <- round(cor(mtcars), 1)
#' @example corr.plot(corr)
corr.plot <- function(data) {
  ggcorrplot(data, hc.order = T,
             type = "lower",
             lab = T,
             lab_size = 3, 
             method = "circle",
             colors = c("tomato2", "white", "springgreen3"),
             ggtheme = theme_bw)
}
#' Create area chart
#' @example area.chart(mtcars, mpg, hp)
area.chart <- function(data, x, y) {
  ggplot(data, aes({{x}}, {{y}})) +
    geom_area()
}
#' Create a diverging bar chart
#' @example mtcars$`car name` <- rownames(mtcars)
#' @example mtcars$mpg_z <- round((mtcars$mpg - mean(mtcars$mpg))/sd(mtcars$mpg), 2)
#' @example mtcars$mpg_type <- ifelse(mtcars$mpg_z < 0, "below", "above")
#' @example mtcars <- mtcars[order(mtcars$mpg_z), ]
#' @example mtcars$`car name` <- factor(mtcars$`car name`, levels = mtcars$`car name`)
#' @example diverging.bar(mtcars, 'car name', mpg_z)
diverging.bar <- function(data, x, y) {
  ggplot(data, aes({{x}}, {{y}})) +
    geom_bar(stat = "identity", width = .5) +
    coord_flip() +
    theme_bw()
}

```

